import {
  LayoutDashboard, Users, CalendarDays, Settings, ClipboardList,
  Vote, Trophy, BarChart2, BarChart3, MapPin
} from 'lucide-react'
import { USER_ROLES } from '@/utils/constants'

export const searchIndex = [
  // Admin Global Pages
  {
    id: 'admin-dashboard',
    title: 'Admin Dashboard',
    path: '/admin',
    keywords: ['admin', 'home', 'overview', 'dashboard', 'stats'],
    category: 'Pages',
    roles: [USER_ROLES.ADMIN],
    icon: LayoutDashboard,
  },
  {
    id: 'admin-organizers',
    title: 'Organizer Management',
    path: '/admin/organizers',
    keywords: ['organizers', 'accounts', 'users', 'create', 'management'],
    category: 'Administration',
    roles: [USER_ROLES.ADMIN],
    icon: Users,
  },
  {
    id: 'admin-events',
    title: 'Global Events',
    path: '/admin/events',
    keywords: ['events', 'global', 'monitor', 'platform', 'all'],
    category: 'Administration',
    roles: [USER_ROLES.ADMIN],
    icon: CalendarDays,
  },
  {
    id: 'admin-settings',
    title: 'System Settings',
    path: '/admin/settings',
    keywords: ['settings', 'configuration', 'system', 'preferences'],
    category: 'Settings',
    roles: [USER_ROLES.ADMIN],
    icon: Settings,
  },
  {
    id: 'admin-audit-logs',
    title: 'Audit Logs',
    path: '/admin/audit-logs',
    keywords: ['audit', 'logs', 'history', 'activity', 'tracking'],
    category: 'Administration',
    roles: [USER_ROLES.ADMIN],
    icon: ClipboardList,
  },

  // Organizer Global Pages
  {
    id: 'org-dashboard',
    title: 'Organizer Dashboard',
    path: '/organizer',
    keywords: ['organizer', 'home', 'overview', 'stats', 'dashboard'],
    category: 'Pages',
    roles: [USER_ROLES.ORGANIZER],
    icon: LayoutDashboard,
  },
  {
    id: 'org-election',
    title: 'Election Module',
    path: '/organizer/election',
    keywords: ['election', 'module', 'voting', 'ballot'],
    category: 'Modules',
    roles: [USER_ROLES.ORGANIZER],
    icon: Vote,
  },
  {
    id: 'org-competition',
    title: 'Competition Module',
    path: '/organizer/competition',
    keywords: ['competition', 'pageant', 'scoring', 'module'],
    category: 'Modules',
    roles: [USER_ROLES.ORGANIZER],
    icon: Trophy,
  },
  {
    id: 'org-polling',
    title: 'Polling Module',
    path: '/organizer/polling',
    keywords: ['polling', 'survey', 'module', 'questions'],
    category: 'Modules',
    roles: [USER_ROLES.ORGANIZER],
    icon: BarChart2,
  },
  {
    id: 'org-reports',
    title: 'Analytics & Reports',
    path: '/organizer/reports',
    keywords: ['reports', 'analytics', 'charts', 'export', 'data'],
    category: 'Reports',
    roles: [USER_ROLES.ORGANIZER],
    icon: BarChart3,
  },

  // Organizer Scoped Pages - Election
  {
    id: 'org-elec-events',
    title: 'Election Events',
    path: '/organizer/election/events',
    keywords: ['election', 'events', 'manage'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: CalendarDays,
  },
  {
    id: 'org-elec-positions',
    title: 'Election Positions',
    path: 'positions',
    scoped: true,
    basePath: '/organizer/election/events',
    keywords: ['positions', 'roles', 'election'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: MapPin,
  },
  {
    id: 'org-elec-candidates',
    title: 'Election Candidates',
    path: 'candidates',
    scoped: true,
    basePath: '/organizer/election/events',
    keywords: ['candidates', 'nominees', 'election'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Users,
  },
  {
    id: 'org-elec-voters',
    title: 'Election Voters',
    path: 'voters',
    scoped: true,
    basePath: '/organizer/election/events',
    keywords: ['voters', 'electorate', 'election'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Users,
  },
  {
    id: 'org-elec-analytics',
    title: 'Election Analytics',
    path: 'analytics',
    scoped: true,
    basePath: '/organizer/election/events',
    keywords: ['election', 'analytics', 'live', 'results'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: BarChart3,
  },

  // Organizer Scoped Pages - Competition
  {
    id: 'org-comp-events',
    title: 'Competition Events',
    path: '/organizer/competition/events',
    keywords: ['competition', 'events', 'pageant'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: CalendarDays,
  },
  {
    id: 'org-comp-workspace',
    title: 'Competition Workspace',
    path: 'workspace',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['workspace', 'competition', 'live', 'scoring'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: LayoutDashboard,
  },
  {
    id: 'org-comp-contestants',
    title: 'Contestants',
    path: 'contestants',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['contestants', 'participants', 'competition'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Users,
  },
  {
    id: 'org-comp-criteria',
    title: 'Judging Criteria',
    path: 'criteria',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['criteria', 'rubric', 'judging', 'competition'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Settings,
  },
  {
    id: 'org-comp-judges',
    title: 'Judges',
    path: 'judges',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['judges', 'panel', 'evaluators', 'competition'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Users,
  },
  {
    id: 'org-comp-rankings',
    title: 'Rankings',
    path: 'rankings',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['rankings', 'leaderboard', 'scores', 'competition'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Trophy,
  },
  {
    id: 'org-comp-analytics',
    title: 'Competition Analytics',
    path: 'analytics',
    scoped: true,
    basePath: '/organizer/competition/events',
    keywords: ['competition', 'analytics', 'stats'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: BarChart3,
  },

  // Organizer Scoped Pages - Polling
  {
    id: 'org-poll-events',
    title: 'Polling Events',
    path: '/organizer/polling/events',
    keywords: ['polls', 'events', 'surveys'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: CalendarDays,
  },
  {
    id: 'org-poll-builder',
    title: 'Form Builder',
    path: 'builder',
    scoped: true,
    basePath: '/organizer/polling/events',
    keywords: ['builder', 'form', 'questions', 'polling'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Settings,
  },
  {
    id: 'org-poll-respondents',
    title: 'Respondents',
    path: 'respondents',
    scoped: true,
    basePath: '/organizer/polling/events',
    keywords: ['respondents', 'answers', 'participants', 'polling'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: Users,
  },
  {
    id: 'org-poll-analytics',
    title: 'Polling Analytics',
    path: 'analytics',
    scoped: true,
    basePath: '/organizer/polling/events',
    keywords: ['polling', 'analytics', 'results'],
    category: 'Events',
    roles: [USER_ROLES.ORGANIZER],
    icon: BarChart3,
  },
]
